version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
    volumes:
      - jenkins-data:/var/jenkins_home
      - ~/.kube:/root/.kube
    user: root  # nécessaire pour que Jenkins puisse accéder à /root/.kube
    restart: unless-stopped

  backend:
    image: ndiaye2024/backend:latest
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/smartphoneDB
    depends_on:
      - mongo

  frontend:
    image: ndiaye2024/frontend:latest
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=http://backend:5000/api 

  mongo:
    image: mongo:5
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
  jenkins-data:
