version: '3.8'

services:
  backend:
    image: ndiaye2024/backend:latest
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/smartphoneDB
    depends_on:
      - mongo

  frontend:
    image: ndiaye2024/frontend:latest
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=http://backend:5000/api 

  mongo:
    image: mongo:5
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
       # 💡 kubeconfig de ton cluster
      - ./jenkins-kubeconfig.yaml:/root/.kube/config
      - ./jenkins_home:/var/jenkins_home
    user: root
    restart: unless-stopped

volumes:
  mongo-data:
