version: '3.8'

services:
  backend:
    image: ndiaye2024/backend:latest
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/smartphoneDB
    depends_on:
      - mongo
    networks:
      - devops-net

  frontend:
    image: ndiaye2024/frontend:latest
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=http://backend:5000/api 
    networks:
      - devops-net

  mongo:
    image: mongo:5
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - devops-net

  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.kube:/root/.kube
      - ./jenkins_home:/var/jenkins_home
    user: root
    restart: unless-stopped
    networks:
      - devops-net

volumes:
  mongo-data:

networks:
  - filrouge
