version: '3.8'

services:
  backend:
    image: ndiaye2024/backend:latest
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/smartphoneDB
    depends_on:
      - mongo
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    networks:
      - filrouge

  frontend:
    image: ndiaye2024/frontend:latest
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=http://backend:5000/api 
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - filrouge

  mongo:
    image: mongo:5
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped
    networks:
      - filrouge

  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./kubeconfig_jenkins.yaml:/root/.kube/config
      - ./jenkins_home:/var/jenkins_home
    user: root
    dns:
      - 8.8.8.8
      - 1.1.1.1
    restart: unless-stopped
    networks:
      - filrouge

volumes:
  mongo-data:

networks:
  filrouge:
    external: true
