apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: filrouge-ingress
  annotations: {}  # ✅ Supprime la réécriture
spec:
  rules:
    - host: filrouge.local
      http:
        paths:
          - path: /frontend
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 80
          - path: /backend
            pathType: Prefix
            backend:
              service:
                name: backend-service
                port:
                  number: 5000
